### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by mickvangelderen**
## Goal of project

DatAViewer lets our software guys, PLC guys, support engineers and customers view the Dat-A Control configuration in 3D.

## Why open source this project

We (the team) would like to invite collaboration on this (currently) toy application.

### Logiqs

1. Any one can take this software, modify it and use it commercially.
2. We can accept contributions (improvements or bug-fixes) from anyone.
3. Our developers need to take care of not disclosing any sensitive data and must behave professionally.

### Partners and customers 

1. Are able to implement improvements and bug-fixes without waiting for Logiqs to allocate time to doing so.
2. These improvements can merged into DatAViewer for Logiqs and it's partners and customers to enjoy.

## Contributions

1. Any one may make contributions to the application or the tooling around it.
2. Logiqs developers must first review the contributions to ensure they are in line with our software standards, our values and our goals for the application.

### CODE REVIEW

**Comment by serra** [comment]
I'd swear this repo had a GPL 3 license earlier, did you rewrite its history @mickvangelderen ?
(That would actually be the right thing to do btw.)

**Comment by serra** [comment]
I approve of the use of the MIT license here.

**Comment by serra** [comment]
I wonder what [unity subscription] we need for this tool. If it does not generate revenue, does the personal plan suffice?

 [unity subscription]: https://store.unity.com/compare-plans

**Comment by mickvangelderen** [comment]
> I'd swear this repo had a GPL 3 license earlier, did you rewrite its history @mickvangelderen ? (That would actually be the right thing to do btw.)

Who knows ;)

**Comment by mickvangelderen** [comment]
> I wonder what [unity subscription](https://store.unity.com/compare-plans) we need for this tool. If it does not generate revenue, does the personal plan suffice?

I think [these additional terms](https://unity3d.com/legal/terms-of-service/software) could be relevant


>  Tier Eligibility
You and everyone using the Unity Software on your behalf must be Tier Eligible at all times.  “Tier Eligible” means that your Total Finances cannot exceed the defined Financial Thresholds for the tier of Unity Software you (or those providing services to you) are using.  Tier Eligibility is measured for the most recent twelve (12) month period.  If you are mid-project, and your Total Finances grow to exceed the Financial Threshold of the Unity Software tier you are using, you do not need to start from scratch - you can simply upgrade your license and continue working. How we measure your Total Finances varies based on who you are.  Financial Thresholds are shown in US currency and your Total Finances will be converted to US currency to determine your Tier Eligibility.

> Total Finances are measured like this:
if you are a Legal Entity using the Unity Software (other than to provide services to someone else), your Total Finances are your gross revenues and/or funding (no matter what the source), or, if you are a Not-for-Profit Entity, your budget for the entire entity (not just the department using the Software),
If you are an individual or a Legal Entity providing services to a third party, your Total Finances is deemed to be your customer or client’s Total Finances, and
if you are an individual using the Unity Software, but not providing services to a third party, your Total Finances are the amount generated in connection with your use of the Unity Software. In this case, your Total Finances would not include amounts you generate from other work (for example, if your day job is as a zookeeper).
By using the Unity Software, you represent and warrant that you are Tier Eligible to use the tier of Unity Software you are using and those being used on your behalf.  You understand that it is your responsibility to maintain complete records establishing your Tier Eligibility and you bear the burden of proving your Tier Eligibility if we ask.    

> Financial Thresholds:
The Financial Threshold for Unity Personal is US $100,000 for the most recent twelve (12) month period.  To be Tier Eligible to use Unity Personal, your Total Finances may not exceed US $100,000.  If your Total Finances exceed US $100,000 you may not use Unity Personal at all, even for internal projects or prototyping.   
The Financial Threshold for Unity Plus is US $ 200,000 for the most recent twelve (12) month period. To be Tier Eligible to use Unity Plus, your Total Finances may not exceed US $200,000.  If your Total Finances exceed $200,000, you may only use Unity Pro.
There is no Financial Threshold for Unity Pro. You do not need to be Tier Eligible to use Unity Pro; Unity Pro may be used by anyone who pays the applicable subscription fees.
For clarity, these Financial Thresholds apply whether or not you use the Unity Software as part of a Unity Plan.

The above would lead me to believe we ought to purchase at least Unity Pro.

**Comment by serra** [comment]
@RvdL86 I suggest we go ahead with open sourcing this code.

**Comment by serra** [comment]
@mickvangelderen ✅ , congrats.

@Remco-Schoeman what about https://github.com/LogiqsAgro/rmq ?

**Pull request merged**
